# selected_folder = "/home/ck/iee-ge/XAI-DIA/image_classification/PyQt-image-annotation-tool/tmp"
selected_folder = "/home/ck/iee-ge/XAI-DIA/image_classification/PyQt-image-annotation-tool/bilder_jpg2"

numLabelsInput = 5

label_headlines = [
    "C1 (nicht gestempelt)",
    "C2 (nich gefüllt)",
    "C3 (kein deckel)",
    "C4 (nicht abgestriffen)",
    "C5 (durchscheinende Füllung)",
    "C6 (Kleckse)",
    "C7 (anderer Fehler)",
    "C8 (keine Form)",
    "C9 (nicht alle betroffen)",
    "C0 (kein Fehler)",
]
