# selected_folder = "/home/ck/iee-ge/XAI-DIA/image_classification/PyQt-image-annotation-tool/tmp"
# selected_folder = "/home/ck/mnt/XAI-DIA-gl/Carsten/bilder_jpg2a/cropped/chunk001_shading_corrected"
selected_folder = "~/XAI-DIA-bilder"

width = 1000
height = 920

numLabelsInput = 5

label_headlines = [
    "leichte durchscheinende Füllung",
    "mittlere durchscheinende Füllung",
    "starke durchscheinende Füllung",
    "Bläschen",
    "Füllung über Rand hinaus",
    "Kratzer/Späne auf Deckel ",
    "Zelle falsch erkannt",
    "sonstiger Fehler",
]
